<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <PackageIcon></PackageIcon>
    <ApplicationIcon>hazmat_xQg_icon.ico</ApplicationIcon>
    <FileVersion>$(Version)</FileVersion>
    <AssemblyVersion>$(Version)</AssemblyVersion>
    <Version>1.8.2.0</Version>
    <Authors>beee</Authors>
    <PackageProjectUrl>https://github.com/mbedda/RustRBLootEditor</PackageProjectUrl>
    <RepositoryUrl>https://github.com/mbedda/RustRBLootEditor.git</RepositoryUrl>
    <PackageLicenseFile>C:\Users\mbedd\source\repos\RustRBLootEditor\RustRBLootEditor\MIT-License.txt</PackageLicenseFile>
    <RollForward>LatestMinor</RollForward>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\blueprintbase.png" />
    <None Remove="Assets\dlcs.json" />
    <None Remove="Assets\items.json" />
    <None Remove="Assets\rust-bg.jpg" />
    <None Remove="Assets\settings.png" />
    <None Remove="Assets\unavailable.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\blueprintbase.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\dlcs.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="hazmat_xQg_icon.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\rust-bg.jpg">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Content Include="Assets\items.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\settings.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Content Include="Assets\unavailable.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HtmlAgilityPack" Version="1.11.42" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Prism.Core" Version="8.1.97" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
    <PackageReference Include="System.Drawing.Common" Version="7.0.0" />
    <PackageReference Include="System.Resources.ResourceManager" Version="4.3.0" />
    <PackageReference Include="VirtualizingWrapPanel" Version="1.5.7" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="UserControls\LootTableItemsUC.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Page Update="UserControls\LootTableItemsUC.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Assets\RustItems\" />
    <Content Include="Assets\RustItems\*.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>
